### ISSUE TITLE
Hard to compile; no clue on how to make it works

### ISSUE THREAD

**Issue by dezzeus** [manosbatsis/corbeans#37]
I have a node with Corda OS 4.3 running.
I've built a simple Spring Boot app-server using Spring MVC and it works.

I strived to make it compile (maybe outdated doc), which I accomplished by adding the JitPack repository for reaching GitHub and by using the `master-SNAPSHOT` version indicator (the last published – v0.5.0, which is not advertised in the docs – used Corda 3.3 by inspecting the dependencies).

As soon as I add corbeans, it fails at runtime with the following:

	java.lang.IllegalStateException: Failed to introspect Class [org.springframework.boot.autoconfigure.jms.artemis.ArtemisEmbeddedServerConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@2e5d6d97]
			at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358) ~[spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:414) ~[spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:743) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_202]
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:742) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:681) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:649) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1608) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:526) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:497) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:619) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:611) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1242) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:869) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
			at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:857) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
			at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:844) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
			at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:795) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
			at com.loanxchain.demo.DemoArtifactApplicationKt.main(DemoArtifactApplication.kt:14) [classes!/:na]
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
			at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
			at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [demo-artifact-0.0.1-SNAPSHOT.jar:na]
			at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [demo-artifact-0.0.1-SNAPSHOT.jar:na]
			at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [demo-artifact-0.0.1-SNAPSHOT.jar:na]
			at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [demo-artifact-0.0.1-SNAPSHOT.jar:na]
	Caused by: java.lang.NoClassDefFoundError: org/apache/activemq/artemis/jms/server/config/JMSConfiguration
			at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_202]
			at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_202]
			at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_202]
			at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
			... 29 common frames omitted
	Caused by: java.lang.ClassNotFoundException: org.apache.activemq.artemis.jms.server.config.JMSConfiguration
			at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_202]
			at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_202]
			at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[demo-artifact-0.0.1-SNAPSHOT.jar:na]
			at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_202]
			... 33 common frames omitted

Steps done:

1. Add `maven(url="https://jitpack.io")` as "repository" in `build.gradle.kts`.
2. Add `implementation("com.github.manosbatsis.corbeans:corbeans-spring-boot-starter:master-SNAPSHOT")` as "dependency" in `build.gradle.kts`.
3. Add & configure `corbeans.nodes.default.[username|password|address]` in `application.properties`.
4. Add a `@Autowired @Qualifier("default") lateinit var service: CordaNodeService` property in the Controller.
5. Provide an endpoint which prints `this.service.proxy().nodeInfo().legalIdentities[0].name.commonName`.
6. Build & invoke task `bootJar`.
7. Run the jar & watch it fail immediately.

**Comment by manosbatsis** [comment]
@dezzeus Nothing to do with corbeans i'm afraid. Boot and Corda are not the best of bed fellows when sharing the same classpath e.g. in tests. Spring MVC goes about it's business but Boot has autoconfiguration beans ready to be triggered by whatever. Corda's dependencies include ActiveMQ and Boot probably thinks it needs a broker.

Sadly there's no one-size-fits-all around dependency/classpath issues between the two platforms. I suggest starting with the [sample/template](https://github.com/manosbatsis/corbeans-yo-cordapp) instead of going from scratch, and gradually add your stuff. More iterative approach and has some not so obvious things covered so you can focus on wrapping your app around the useful bits..

If you need help feel free to post, always helps me improve the docs a bit.

**Comment by dezzeus** [comment]
Thank you very much @manosbatsis, I'll give a try to the template… :)

**Comment by muhamadto** [comment]
@dezzeus I'm not sure what ActiveMQ is used for as I'm checking Corda for the first time but to avoid the exception above you have two options

1. Exclude `org.apache.activemq:artemis-amqp-protocol` it will start,

```
<dependency>
    <groupId>com.github.manosbatsis.corbeans</groupId>
    <artifactId>corbeans-spring-boot-corda</artifactId>
    <version>${corbeans_version}</version>
    <scope>compile</scope>
    <exclusions>
        <exclusion>
            <groupId>org.apache.activemq</groupId>
            <artifactId>artemis-amqp-protocol</artifactId>
        </exclusion>
        </exclusions>
</dependency>
```
2. Alternatively, you can exclude the autoconfiguration in your SpringBootApplication 

> @SpringBootApplication(exclude = arrayOf(ArtemisAutoConfiguration::class))

I'm doing so while getting started. If I find I need ActiveMQ later I will configure it. 

As I mentioned before, I'm just getting started, So, if your case is more advanced you may need to actually configure ActiveMQ correctly
